{% set name = "pgcli" %}
{% set version = "3.0.0" %}
{% set sha256 = "4920225838e8004ae6d2ec42f566e0a8b99c4bd42bc2c876d0de8501da0a4082" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pgcli=pgcli.main:cli

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pgspecial >=1.11.8
    - click >=4.1
    - cli_helpers >=1.2.1
    - pygments >=2.0
    - prompt_toolkit >=2.0.6,<3.0.0
    - psycopg2 >=2.8
    - sqlparse >=0.3.0,<0.4
    - configobj >=5.0.6
    - humanize >=0.5.1
    - wcwidth >=0.1.6
    - setproctitle >=1.1.9
    - tabulate

test:
  imports:
    - pgcli
    - pgcli.packages
    - pgcli.packages.parseutils
    - pgcli.packages.pgliterals
  commands:
    - pgcli --help

about:
  home: http://pgcli.com
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  # xref: https://github.com/dbcli/pgcli/pull/728
  #license_file: LICENSE.txt
  summary: CLI for Postgres Database. With auto-completion and syntax highlighting.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/dbcli/pgcli

extra:
  recipe-maintainers:
    - mariusvniekerk
    - dhirschfeld
