{% set name = "pgcli" %}
{% set version = "2.0.2" %}
{% set sha256 = "04f4d3f4dd61d2d165eb2fd8d77879357489a74ca1446cd09fa375c7561392dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pgcli=pgcli.main:cli

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pgspecial >=1.11.2
    - click >=4.1
    - cli_helpers >=1.0.1
    - pygments >=2.0
    - prompt_toolkit >=2.0.0,<3.0.0
    - psycopg2 >=2.7.4
    - sqlparse >=0.2.2,<0.3.0
    - configobj >=5.0.6
    - humanize >=0.5.1
    - wcwidth >=0.1.6
    - setproctitle >=1.1.9
    - tabulate

test:
  imports:
    - pgcli
    - pgcli.packages
    - pgcli.packages.parseutils
    - pgcli.packages.pgliterals
  commands:
    - pgcli --help

about:
  home: http://pgcli.com
  license: BSD-3-Clause
  license_family: BSD
  # xref: https://github.com/dbcli/pgcli/pull/728
  #license_file: LICENSE.txt
  summary: 'CLI for Postgres Database. With auto-completion and syntax highlighting.'
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/dbcli/pgcli

extra:
  recipe-maintainers:
    - mariusvniekerk
