{% set name = "pgcli" %}
{% set version = "4.0.1" %}
{% set sha256 = "f2feea2099ce1ad5e8a9d5d93b0edaf60dc61e97b21b75e91d9723939ce53bd2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pgcli=pgcli.main:cli

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - pgspecial >=2.0.0
    - click >=4.1
    - cli_helpers >=2.2.1
    - pendulum >=2.1.0
    - pygments >=2.0
    - prompt_toolkit >=3.0.0,<4.0.0
    - psycopg >=3.0.14
    - sqlparse >=0.3.0,<0.5
    - configobj >=5.0.6
    - setproctitle >=1.1.9

test:
  imports:
    - pgcli
    - pgcli.packages
    - pgcli.packages.parseutils
    - pgcli.packages.pgliterals
  commands:
    - pgcli --help

about:
  home: http://pgcli.com
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  # xref: https://github.com/dbcli/pgcli/pull/728
  #license_file: LICENSE.txt
  summary: CLI for Postgres Database. With auto-completion and syntax highlighting.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/dbcli/pgcli

extra:
  recipe-maintainers:
    - mariusvniekerk
    - dhirschfeld
