travis:
  secure:
    BINSTAR_TOKEN: VZY78VUe/JJ2Fw74l4mwI28Yx2nssgY8POEVqLC9NIbF60VSg+t2Js/jO0N4B9M0eW5ctL0GLSZM0NkejNeMrc015Jl9xNWQeEN+0koRk3em0HtKZ+XiAzAX/EEK/PBbIAIT2exf0QhVrOVsPUHzM73srI73QAK+rnGNDNUY8Gh44wZP2gCTHWejR8JxXJ9PeBl2+1ZEzTppZwVyDjvdBdFFTG/EnyXnythK+yjF0Le38rz+Z4aTqppXgjU1H8gUK18Wg8OWQfxX/IL7wBkCU1dZ2iqjpWszSE1jhJC9gqCo8wIzTMzMFi7w7xq1kdsGGX7Kw/vHmyolLnEdq12fCv1NAP0sNsgd9/Tqo+LXvFkJiLphrXcIWJ5LhOHZeFCUFJeVXYOPSZGQPzHSfXshpK+uwD0jsS4HLxuGPEhdGG/3PykEyps0BW6KUIm9VxJ79TOxrbStFSBEKoqdw1SJwHx1FKipbYCsTiYf9RxGrlxALFGur2nQdYCzz1wEwgZrzPgFyNp5KyKa3eFV/7gvYMCVn2DRhuPuvzrOWzXPAH3YsEUyP3EPD6/GFwaKRVVvyUMeFSoI7wKtgM047qFumrZdroVtCJU8fFIeADYIM/IycQRW2YcLBSs2gA4whSF2FfWCPH4WNAoJ47kWMeav2DiC5WGmHdw2ehqyKOs/dP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
